# Generated by Django 5.2.11 on 2026-03-04 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_firstname',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator(message='This field can only contain alphanumeric characters (a-z, A-Z, 0-9) and spaces. No special characters allowed.', regex='^[a-zA-Z0-9 ]+$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_lastname',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator(message='This field can only contain alphanumeric characters (a-z, A-Z, 0-9) and spaces. No special characters allowed.', regex='^[a-zA-Z0-9 ]+$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_login',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='This field can only contain alphanumeric characters (a-z, A-Z, 0-9). No spaces or special characters allowed.', regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
